### ISSUE TITLE
UI and Layout

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#116]
There should be some changes in the layout of the Nexpert Application. 
The Layout should looks exactly like this:

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/b136697c-490b-4581-87d1-18ee9b7d4585)

The icons resources can be found in the attachments.

[Resources First Page No Data.zip](https://github.com/ioannexpert/nexpertERP/files/14524949/Resources.First.Page.No.Data.zip)

This is applicable to all Documents pages

**Comment by DanDEV1405** [comment]
Estimat: 1 ora

**Comment by ioannexpert** [comment]
E ok

**Comment by DanDEV1405** [comment]
Avem nevoie de icon pentru data analysis
