### ISSUE TITLE
Add Favorites to the main menu

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#118]
All the favorites choosen by the user should be displayed in the left menu under Pages as described below:

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/e3239e62-8736-4fa4-99a5-a13f20b2ba79)

**Comment by DanDEV1405** [comment]
Estimat: 1 ora

**Comment by ioannexpert** [comment]
E ok

**Comment by ioannexpert** [comment]
The Favourites should be displayed in the Pages menu and it should appear instantly,
