### ISSUE TITLE
Posibility to Modify Documents for Super User

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#119]
There should be 2 entities: Super Admin, and Companies. The Super Admin should have a different views and modules, e.g. create and update new documents for Companies.

Also as a test I should have  the posibility  to connect with the two different users: Super Admin and Companies(Refurb1 and Refurb2).

**Comment by DanDEV1405** [comment]
Estimat: 7 ore

**Comment by ioannexpert** [comment]
E ok.
