### ISSUE TITLE
Click on the card should go to sheets

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#120]
The documents card in the page should act as a link to sheets page. The cursor should be pointer(hand)

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/3acb4048-594f-4e2e-8ce0-856746dd78c4)

**Comment by DanDEV1405** [comment]
Estimat: 0.5 ore

**Comment by ioannexpert** [comment]
OK
