### ISSUE TITLE
+ sign on the page should be big and right

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#121]
No documents

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/e0f22dee-35d0-4054-b2a3-748b00651dda)

With one or multiple documents

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/5f795175-4b9d-47bb-9dba-104880a5cdfd)

**Comment by DanDEV1405** [comment]
Estimat: 0.5 ore

**Comment by ioannexpert** [comment]
OK
