### ISSUE TITLE
Save the data in the sheet

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#125]
If a new data was entered in a sheet then a star * should be displayed on the sheet tab name. If the user will leave the sheet the sistem should ask if it would like to save the sheet or not. Also there should be new button save all in the home menu.
1. User change some data on a sheet
2. A small star should be displayed next to the sheet tab name

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/5e614045-56ec-411d-8b3c-af941bb68df4)

3 if it leaves the sheet and it is not saved then a mesage should be display to save the data or not

**Comment by DanDEV1405** [comment]
Estimat: 2 ore

**Comment by ioannexpert** [comment]
OK

**Comment by ioannexpert** [comment]
It is ok now if the user leaves the sheet but if the user click on save button and leaves the sheet the message still appears that the sheet is not saved.
