### ISSUE TITLE
SignIn Page

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#148]
Please create the Sign in web page as per following specs

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/12117d84-dd6c-48e5-9047-b254c885f098)

please use the backgrounds from attachments

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/7bb6ece9-dca2-4084-b60c-d98ae61c45fc)
![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/6f7def4b-b827-42d9-8bfd-5f628c654338)

**Comment by DanDEV1405** [comment]
Estimat: 1.5 ore
