### ISSUE TITLE
Create following modules

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#154]
Clinical Data Management

Patient Demographics: Stores basic personal information about patients.
Patient History: Contains all historical health information including medical, family, and social histories.
Clinical Documentation: Used for recording all details of patient encounters, treatments, and clinical notes.
Order Entry (CPOE): Facilitates the placement of orders for tests, procedures, and other services.
Medication Management: Manages all aspects of prescribing and tracking medications.
Lab Integration: Incorporates laboratory results directly into the patient’s record.
Imaging Integration: Manages and integrates radiological and other imaging data.

Administrative and Scheduling

Scheduling: Manages appointments, including bookings, rescheduling, and cancellations.
Billing Module: Handles all aspects of billing, insurance processing, and payments.

Reporting and Compliance

Reporting and Analytics: Provides tools for generating various reports needed for clinical, operational, and regulatory purposes.
Health Information Exchange (HIE) Integration: Enables the sharing of patient information across different healthcare systems for better coordinated care.

Patient Engagement and Communication

Electronic Prescribing: Allows direct electronic sending of prescriptions to pharmacies.
Patient Portal: Offers patients access to their health records, appointment scheduling, communication with healthcare providers, and medication refills.

**Comment by DanDEV1405** [comment]
Estimat: N/A
Astept sedinta de marti, 16.04 sa inteleg mai bine workflow pentru a estima
