### ISSUE TITLE
Data view mode

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#168]
There should be 2 view modes as shown in the picture below:

![Image](https://github.com/ioannexpert/nexpertERP/assets/146850956/51d3e3d4-6525-43d4-a7b6-2a8278b380a0)

Functionalities

When the user click on Split mode view the app should split  the screen horizontaly and at the begining what it sees on top it should be seen on the bottom

Also there should be the posibility to revert to list view

**Comment by DanDEV1405** [comment]
Estimat: 8 ore
