### ISSUE TITLE
Posibility to see a data in a sheet only based on hyperlink

### ISSUE THREAD

**Issue by ioannexpert** [ioannexpert/nexpertERP#169]
If the user select 1 or more records in one sheet and click on another sheet if there is a hyperlink between the 2 sheets then the records should be displayed only bases on the selected records in the first sheet.
Example:
I have the following Patient Numbers in Patients
1
2
3
4

In the Imaging sheet there are the following records with the following patient number:
1
1
2
2
3
3
4
4

if the user select the records with patient number 1 then when it clicks on the Imaging sheet  it should see only imaging for number 1.
if the user select the records with patient number 1 and 2 then when it clicks on the Imaging sheet  it should see only imaging for number 1 and 2.

And so on. This should also work in Split mode View and Card view

**Comment by DanDEV1405** [comment]
Estimat: N/A
Explicat mai in detaliu, deja aavem hyperlink in functie de o valoare. Nu inteleg de ce user ar trebui sa selecteze una sau mai multe

**Comment by ioannexpert** [comment]
Obsolete. See #187
